name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Tests slibc
    runs-on: ubuntu-latest

    steps:
    - name: Install Clang
      run: sudo apt-get install clang && export CC=clang

    - uses: actions/checkout@v1
    
    - name: Install slibc
      run: mkdir -p build && cd build && cmake -S .. -B . && sudo make install
      env:
        CC: clang

    - name: Make Tests
      run: mkdir -p tests/build && cd tests/build && cmake -S .. -B . && make
      env:
        CC: clang

    - name: Run Tests
      run: tests/build/tests 2> /dev/null
      env:
        CC: clang
        CXX: clang++